export const TOGGLE_MENU = 'TOGGLE_MENU';
export const REQUEST_ALL_RECIPES = 'REQUEST_ALL_RECIPES';
export const RECEIVE_ALL_RECIPES = 'RECEIVE_ALL_RECIPES';
export const UPDATE_RECIPE_REQ = 'UPDATE_RECIPE_REQ';
export const UPDATE_RECIPE_RES = 'UPDATE_RECIPE_RES';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const REQUEST_RECIPE = 'REQUEST_RECIPE';
export const RECEIVE_RECIPE = 'RECEIVE_RECIPE';


